/* Additional record code for bModel generated by the OpenModelica Compiler OpenModelica 1.13.0. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

