/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Dec 04 2019 20:29:17 GMT-0600 (GMT-06:00).
 */

define(['plotlyjs',
        'blob/BlobClient',
        'css!./styles/newgraphWidget.css']
    , function (Plotly,BlobClient) {
    'use strict';



    var WIDGET_CLASS = 'newgraph';






    function newgraphWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this._bc = new BlobClient({logger:this._logger});


        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    };


    // global variable, selected attribute
    //var selected_attribute;

    // div element for ploty graph
    var myDiv = document.createElement("myDiv");
    myDiv.style.cssText = 'position:relative;top: 10px;left: 120px;font-size: 40px;text-align: center';

    // update the value for x
    var x_axis = [];

    // update the value for y
    var y_axis = [];

    // attribute list value
    var attribute_list = [];

    // select list
    var selectList = document.createElement("select");
    selectList.id = "mySelect";
    selectList.style.cssText = 'position:relative;top: 10px;left: 120px;font-size: 40px;text-align: center';

    // button
    var button = document.createElement("input");
    button.type = "button";
    button.value = "Generate a xy graph";
    button.style.cssText = 'position:relative;top: 10px;left: 150px;font-size: 40px;text-align: center';

    newgraphWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header
        this._el.append('<h3>Draw a Graph:</h3>');

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    // Collecting date method
    newgraphWidget.prototype.collectData = function () {

    }

    newgraphWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Function that will generate the button and plot
    // This function should be passed in a hash value which would
    // get information from blob client
    newgraphWidget.prototype.setVissualizer = function(hash_val){
        this._bc.getObjectAsString(hash_val, function(js,output_csv){
            if (output_csv) {
                //document.write(output_csv);
                let lines = output_csv.split('\n');
                //document.write(lines[0]);
                // The first line would be the header
                let first_row = lines[0].split(',');
                //document.write(first_row[0]);
                // store data in a 2d array
                let attribute_number = first_row.length;
                //document.write(attribute_number);
                let arr = new Array(lines.length - 1);
                for (let index = 1; index < lines.length - 1; index++) {
                    arr[index - 1] = new Array(attribute_number);
                    // split single line by ','
                    let temp = lines[index].split(',');
                    // parse the data to int and store in the table
                    for (let n = 0; n < attribute_number; n++) {
                        arr[index - 1][n] = parseFloat(temp[n]);
                    }
                }
                //document.write(arr);
                // the attribute variable
                for (let i = 1; i < first_row.length; i++) {
                    attribute_list.push(first_row[i]);
                }
                //document.write(attribute_list);

                // Generate the dropdown list elements
                for (let j = 0; j < attribute_list.length; j++) {
                    let option = document.createElement("option");
                    option.value = attribute_list[j];
                    option.text = attribute_list[j];
                    selectList.add(option);
                }
                // button on click function
                button.onclick = function () {
                    // get the Attribute from selector
                    let selected_index = selectList.selectedIndex;
                    //selected_attribute = selectList.options[selected_index].text;
                    // Pass the date to the graph array
                    for (let a = 0; a < arr[0].length; a++) {
                        x_axis.push(arr[0][a]);
                        y_axis.push(arr[selected_index + 1][a]);
                    }
                    // plot the graph
                    Plotly.plot( myDiv, [{
                        x: x_axis,
                        y: y_axis }], {
                        margin: { t: 0 } } );
                };

            } else {
                document.write("null object");
            }
        });
    };


    // Adding/Removing/Updating items
    newgraphWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
                desc.childrenIds.length + ' ' + label + '.';

            // this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    newgraphWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    newgraphWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    newgraphWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };


    newgraphWidget.prototype.onBackgroundDblClick = function () {
        //this._el.append('<div>Background was double-clicked!!</div>');

        this._el.append(selectList);
        this._el.append(button);
        this._el.append(myDiv);

    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    newgraphWidget.prototype.destroy = function () {
    };

    newgraphWidget.prototype.onActivate = function () {
        this._logger.debug('newgraphWidget has been activated');
    };

    newgraphWidget.prototype.onDeactivate = function () {
        this._logger.debug('newgraphWidget has been deactivated');
    };

    return newgraphWidget;
});
